// Generated by verification/generate_crc.py; CRC16 0x1021, ten MSB-first bits.
function automatic[15:0]step(input[15:0]old,input[9:0]w);
begin
 step[0]=((old[6] ^ (old[10] ^ old[14])) ^ (w[0] ^ (w[4] ^ w[8])));
 step[1]=((old[7] ^ (old[11] ^ old[15])) ^ (w[1] ^ (w[5] ^ w[9])));
 step[2]=((old[8] ^ old[12]) ^ (w[2] ^ w[6]));
 step[3]=((old[9] ^ old[13]) ^ (w[3] ^ w[7]));
 step[4]=((old[10] ^ old[14]) ^ (w[4] ^ w[8]));
 step[5]=(((old[6] ^ old[10]) ^ (old[11] ^ (old[14] ^ old[15]))) ^ ((w[0] ^ w[4]) ^ (w[5] ^ (w[8] ^ w[9]))));
 step[6]=(((old[7] ^ old[11]) ^ (old[12] ^ old[15])) ^ ((w[1] ^ w[5]) ^ (w[6] ^ w[9])));
 step[7]=((old[8] ^ (old[12] ^ old[13])) ^ (w[2] ^ (w[6] ^ w[7])));
 step[8]=((old[9] ^ (old[13] ^ old[14])) ^ (w[3] ^ (w[7] ^ w[8])));
 step[9]=((old[10] ^ (old[14] ^ old[15])) ^ (w[4] ^ (w[8] ^ w[9])));
 step[10]=((old[0] ^ old[11]) ^ (old[15] ^ (w[5] ^ w[9])));
 step[11]=(old[1] ^ (old[12] ^ w[6]));
 step[12]=(((old[2] ^ old[6]) ^ (old[10] ^ old[13])) ^ ((old[14] ^ w[0]) ^ (w[4] ^ (w[7] ^ w[8]))));
 step[13]=(((old[3] ^ old[7]) ^ (old[11] ^ old[14])) ^ ((old[15] ^ w[1]) ^ (w[5] ^ (w[8] ^ w[9]))));
 step[14]=((old[4] ^ (old[8] ^ old[12])) ^ ((old[15] ^ w[2]) ^ (w[6] ^ w[9])));
 step[15]=((old[5] ^ old[9]) ^ (old[13] ^ (w[3] ^ w[7])));
end
endfunction
