"""Generate the GF(2) matrix for ten MSB-first bits, polynomial 0x1021."""
from pathlib import Path
import sys
state=[1<<k for k in range(16)]
for k in range(9,-1,-1):
    feedback=state[15]^(1<<(16+k))
    state=[0]+state[:15]
    state=[v^(feedback if (0x1021>>i)&1 else 0) for i,v in enumerate(state)]
def balanced(xs):
    if len(xs)==1:return xs[0]
    n=len(xs)//2
    return '('+balanced(xs[:n])+' ^ '+balanced(xs[n:])+')'
lines=['// Generated by verification/generate_crc.py; CRC16 0x1021, ten MSB-first bits.',
       'function automatic[15:0]step(input[15:0]old,input[9:0]w);','begin']
for i,mask in enumerate(state):
    terms=[f'old[{b}]' if b<16 else f'w[{b-16}]' for b in range(26) if (mask>>b)&1]
    lines.append(f' step[{i}]='+balanced(terms)+';')
lines+=['end','endfunction','']
text='\n'.join(lines)
p=Path(__file__).resolve().parents[1]/'rtl/pt_crc.vh'
if '--check' in sys.argv:
    assert p.read_text()==text,'generated CRC equations are stale'
else:p.write_text(text)
