#!/usr/bin/env bash
set -euo pipefail
runner="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)/scripts/run_analog_flow.sh"
exec "$runner" --label cml-vco-bank \
  --source-rel ip/blocks/analog/wireline_serdes/pll \
  --timeout 45m --cpus 2 --memory 4g --command /src/container_vco_bank.sh \
  --copy cml_vco_delay_fast-drc.rpt:cml-vco-fast-drc-last.rpt \
  --copy cml_vco_delay_fast-lvs.out:cml-vco-fast-lvs-last.out \
  --copy cml_vco_delay_fast.pex.spice:cml-vco-fast-pex-last.spice \
  --copy cml_vco_delay_fast-layout.png:cml-vco-fast-layout-last.png \
  --copy fast-ring.json:cml-vco-fast-ring-last.json \
  --copy cml_vco_delay_ultra_fast-drc.rpt:cml-vco-ultra-fast-drc-last.rpt \
  --copy cml_vco_delay_ultra_fast-lvs.out:cml-vco-ultra-fast-lvs-last.out \
  --copy cml_vco_delay_ultra_fast.pex.spice:cml-vco-ultra-fast-pex-last.spice \
  --copy cml_vco_delay_ultra_fast-layout.png:cml-vco-ultra-fast-layout-last.png \
  --copy cml_vco_delay_slow-drc.rpt:cml-vco-slow-drc-last.rpt \
  --copy cml_vco_delay_slow-lvs.out:cml-vco-slow-lvs-last.out \
  --copy cml_vco_delay_slow.pex.spice:cml-vco-slow-pex-last.spice \
  --copy cml_vco_delay_slow-layout.png:cml-vco-slow-layout-last.png \
  --copy slow-ring.json:cml-vco-slow-ring-last.json \
  --copy cml_vco_delay_high_gain-drc.rpt:cml-vco-high-gain-drc-last.rpt \
  --copy cml_vco_delay_high_gain-lvs.out:cml-vco-high-gain-lvs-last.out \
  --copy cml_vco_delay_high_gain.pex.spice:cml-vco-high-gain-pex-last.spice \
  --copy cml_vco_delay_high_gain-layout.png:cml-vco-high-gain-layout-last.png \
  --copy cml_vco_delay_ss_ff-drc.rpt:cml-vco-ss-ff-drc-last.rpt \
  --copy cml_vco_delay_ss_ff-lvs.out:cml-vco-ss-ff-lvs-last.out \
  --copy cml_vco_delay_ss_ff.pex.spice:cml-vco-ss-ff-pex-last.spice \
  --copy cml_vco_delay_ss_ff-layout.png:cml-vco-ss-ff-layout-last.png \
  --copy ss-ff-ring.json:cml-vco-ss-ff-ring-last.json \
  --copy cml_vco_delay_ss_ss-drc.rpt:cml-vco-ss-ss-drc-last.rpt \
  --copy cml_vco_delay_ss_ss-lvs.out:cml-vco-ss-ss-lvs-last.out \
  --copy cml_vco_delay_ss_ss.pex.spice:cml-vco-ss-ss-pex-last.spice \
  --copy cml_vco_delay_ss_ss-layout.png:cml-vco-ss-ss-layout-last.png \
  --copy ss-ss-ring.json:cml-vco-ss-ss-ring-last.json \
  --copy cml_vco_delay_margin_slow-drc.rpt:cml-vco-margin-slow-drc-last.rpt \
  --copy cml_vco_delay_margin_slow-lvs.out:cml-vco-margin-slow-lvs-last.out \
  --copy cml_vco_delay_margin_slow.pex.spice:cml-vco-margin-slow-pex-last.spice \
  --copy cml_vco_delay_margin_slow-layout.png:cml-vco-margin-slow-layout-last.png \
  --copy margin-slow-ring.json:cml-vco-margin-slow-ring-last.json \
  --copy cml_vco_delay_margin_fast-drc.rpt:cml-vco-margin-fast-drc-last.rpt \
  --copy cml_vco_delay_margin_fast-lvs.out:cml-vco-margin-fast-lvs-last.out \
  --copy cml_vco_delay_margin_fast.pex.spice:cml-vco-margin-fast-pex-last.spice \
  --copy cml_vco_delay_margin_fast-layout.png:cml-vco-margin-fast-layout-last.png \
  --copy margin-fast-ring.json:cml-vco-margin-fast-ring-last.json \
  --copy vco-bank-result.json:cml-vco-bank-result-last.json \
  --copy layout-vco-bank.png:cml-vco-bank-layout-last.png
